### ISSUE TITLE
artisan config:cache падает с ошибкой Route [admin.dashboard] not defined.

### ISSUE THREAD

**Issue by dipyalov** [LaravelRUS/SleepingOwlAdmin#131]
Это происходит потому, что при вызове этой команды загрузка системы происходит дважды.
Первый раз для того, чтобы очистить конфигурацию, второй - чтобы закешировать.

Обращение к роуту admin.dashboard происходит при конструировании навигации - там есть формирование урла по этому роуту.

При второй загрузке однако роут не попадает в список доступных, потому что метод AdminServiceProvider->registerCustomRoutes для загрузки роутов использует require_once и повторно уже ничего не делает
![image](https://cloud.githubusercontent.com/assets/1793216/15612958/4171018c-2431-11e6-9aee-4dcf3b81353d.png)

Я у себя заменил require_once на require, но, к сожалению, у меня нет достаточной компетенции, чтобы сказать, какие последствия за собой это повлечет. 

Пожалуйста, исправьте это поведение на верное.

**Comment by tiagomapmarques** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/pull/85

"When extending any of your Display/Column or Form/Element classes inside a folder that is being autoloaded, your code tried to require them again, causing a "Cannot redeclare class" error."

If you want people to contribute/extend SleepingOwl's functionality, the "require" will make every Display/Column or Form/Element break. Try it yourselves:
1) Get Laravel + SleepingOwl;
2) make a class to extend Display/Column ( "class SomeName extends Text" );
3) composer install -> "Cannot redeclare class"

Also, having "require" in your code, you either know exactly what you are doing and dont have any dependencies (this is automatically false because you depend on laravel), or you are opening your application to multiple vulnerabilities on run-time (the worst time for your code to break, imo).

If your code (SleepingOwl) or any extensions break by replacing "require" with "require_once" (it does btw), then your code (and/or the logic behind it) is fundamentally broken...
