### ISSUE TITLE
Missed "form" tag for first entry in related table view.

### ISSUE THREAD

**Issue by protectedfor** [LaravelRUS/SleepingOwlAdmin#645]
Hello everyone.

I found one bug with deleting related entry in form -> https://s.mail.ru/9RJm/SHHuDYYsb

The problem is that delete button in related table doesn't work because it doesn't generates `<form>` element for it. It's appears only for the first record. Here is a screenshots: 
1. https://s.mail.ru/LNVo/NksBNfeWD
2. https://s.mail.ru/Dxco/PmcNQLvZy

On first screenshot system didn't generate `form` tag for input that is why this record can't be deleted.

On second screenshot everything is ok and `form` element presented and entry can be deleted successfully.

Please fix this bug.

**Comment by aios** [comment]
@protectedfor can you write on telegram group - it be fastest to research with your data)

**Comment by aios** [comment]
![image](https://user-images.githubusercontent.com/737550/28202903-1799b72a-6880-11e7-9e4f-11d80d53bf73.png)

Can't repro

All systems working by this question

**Comment by eugenem** [comment]
Not that there is no <form> for the first button, but it's not working, as it resides inside the large form (of the main editor), which is invalid HTML:

<form - main editor>
<form - delete></form>
<form - delete></form>
</form>

I think you've got to use something else for deletion besides forms. Maybe store id as data and post with ajax, instead of submitting the form...
